# pip install cryptography
import os
import base64
import argparse
import secrets

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
from cryptography.exceptions import InvalidTag

"""
This script provides a simple command-line interface for encrypting and decrypting files
using AES-256 GCM (Galois/Counter Mode). It also includes functionality to generate
a secure, base64-encoded encryption key.

AES-256 GCM is an authenticated encryption mode, meaning it not only encrypts the data
but also ensures its integrity and authenticity. Any tampering with the ciphertext
will be detected during decryption, preventing malicious modifications.

Key Features:
- Generate a 256-bit (32-byte) key, base64-encoded for easy storage and use.
- Encrypt a file using a provided key, producing an output file containing the
  nonce, authentication tag, and ciphertext.
- Decrypt a file using the same key, verifying its integrity.

Usage Examples (run from your terminal):
1. Install the required library:
   pip install cryptography

2. Generate a key and save it securely:
   python simple_encryptor.py --generate-key
   (Copy the printed key, e.g., 'YOUR_BASE64_KEY')

3. Create a dummy file for encryption:
   echo "This is a secret message." > original.txt

4. Encrypt the file:
   python simple_encryptor.py --encrypt --input original.txt --output encrypted.bin --key YOUR_BASE64_KEY

5. Decrypt the file:
   python simple_encryptor.py --decrypt --input encrypted.bin --output decrypted.txt --key YOUR_BASE64_KEY

6. Verify decryption (output to screen):
   cat decrypted.txt

Important Security Note:
- The security of this script relies entirely on the secrecy of the key.
  Never share your encryption key with unauthorized parties.
- Always use a unique key for each set of sensitive files.
- The key generated by this script is random and strong.
- This script does NOT handle key management or secure key storage.
  It assumes you will store and provide the key securely.
"""

# AES-256 uses a 32-byte key.
KEY_SIZE = 32
# GCM mode uses a 12-byte (96-bit) nonce. This is crucial for security and must be unique per encryption.
NONCE_SIZE = 12
# GCM authentication tag size is typically 16 bytes (128 bits).
TAG_SIZE = 16
# Chunk size for reading/writing files to handle large files efficiently.
CHUNK_SIZE = 4096

def generate_key():
    """
    Generates a secure 256-bit (32-byte) random key and returns it
    as a base64-encoded string.
    """
    key = secrets.token_bytes(KEY_SIZE)
    return base64.urlsafe_b64encode(key).decode('utf-8')

def encrypt_file(input_filepath: str, output_filepath: str, b64_key: str):
    """
    Encrypts a file using AES-256 GCM.

    The output file format is: [NONCE (12 bytes)] + [CIPHERTEXT] + [TAG (16 bytes)].

    Args:
        input_filepath (str): Path to the file to encrypt.
        output_filepath (str): Path where the encrypted file will be saved.
        b64_key (str): The base64-encoded encryption key.
    """
    try:
        # Decode the base64 key back to bytes
        key = base64.urlsafe_b64decode(b64_key)
        if len(key) != KEY_SIZE:
            raise ValueError(f"Key must be {KEY_SIZE} bytes (256-bit) after decoding. Got {len(key)} bytes.")

        # Generate a unique nonce (Initialization Vector) for each encryption.
        # This is CRITICAL for security with GCM mode. Never reuse a nonce with the same key.
        nonce = os.urandom(NONCE_SIZE)

        # Initialize the AES cipher with the key and GCM mode with the nonce.
        # GCM mode provides authenticated encryption, meaning it also verifies data integrity.
        cipher = Cipher(algorithms.AES(key), modes.GCM(nonce), backend=default_backend())
        encryptor = cipher.encryptor()

        with open(input_filepath, 'rb') as infile, open(output_filepath, 'wb') as outfile:
            # Write the nonce at the beginning of the output file.
            # It's needed for decryption and does not need to be secret.
            outfile.write(nonce)

            # Read the input file in chunks, encrypting each one.
            while True:
                chunk = infile.read(CHUNK_SIZE)
                if not chunk:
                    break
                # Update the encryptor with the plaintext chunk.
                # It encrypts and buffers the data.
                ciphertext_chunk = encryptor.update(chunk)
                outfile.write(ciphertext_chunk)

            # Finalize the encryption. This handles any remaining buffered data
            # and computes the authentication tag.
            encryptor.finalize()
            tag = encryptor.tag

            # Write the authentication tag at the end of the ciphertext.
            # The tag is used during decryption to verify the data's integrity.
            outfile.write(tag)

        print(f"Success: File '{input_filepath}' encrypted to '{output_filepath}'.")

    except FileNotFoundError:
        print(f"Error: Input file '{input_filepath}' not found.")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred during encryption: {e}")


def decrypt_file(input_filepath: str, output_filepath: str, b64_key: str):
    """
    Decrypts a file encrypted with AES-256 GCM.

    Expects the input file format: [NONCE (12 bytes)] + [CIPHERTEXT] + [TAG (16 bytes)].

    Args:
        input_filepath (str): Path to the encrypted file.
        output_filepath (str): Path where the decrypted file will be saved.
        b64_key (str): The base64-encoded encryption key.
    """
    try:
        # Decode the base64 key back to bytes
        key = base64.urlsafe_b64decode(b64_key)
        if len(key) != KEY_SIZE:
            raise ValueError(f"Key must be {KEY_SIZE} bytes (256-bit) after decoding. Got {len(key)} bytes.")

        with open(input_filepath, 'rb') as infile, open(output_filepath, 'wb') as outfile:
            # Read the nonce from the beginning of the encrypted file.
            nonce = infile.read(NONCE_SIZE)
            if len(nonce) != NONCE_SIZE:
                raise ValueError("Encrypted file is too short or malformed (nonce missing or incomplete).")

            # Determine the total size of the file to correctly locate the tag.
            infile.seek(0, os.SEEK_END)
            total_size = infile.tell()

            # The ciphertext and tag combined size is the total file size minus the nonce size.
            ciphertext_and_tag_size = total_size - NONCE_SIZE

            # Check if there's enough data for at least a tag.
            if ciphertext_and_tag_size < TAG_SIZE:
                raise ValueError("Encrypted file is too short or malformed (tag missing or incomplete).")

            # Seek to the position where the tag starts (total_size - TAG_SIZE).
            infile.seek(total_size - TAG_SIZE)
            tag = infile.read(TAG_SIZE)

            # Rewind the file pointer to the beginning of the ciphertext (after the nonce).
            infile.seek(NONCE_SIZE)

            # Initialize the AES cipher with the key and GCM mode with the nonce.
            cipher = Cipher(algorithms.AES(key), modes.GCM(nonce), backend=default_backend())
            decryptor = cipher.decryptor()

            # Read the ciphertext in chunks.
            # The amount of ciphertext is total_size - NONCE_SIZE - TAG_SIZE.
            bytes_to_decrypt = ciphertext_and_tag_size - TAG_SIZE
            bytes_read = 0

            while bytes_read < bytes_to_decrypt:
                # Read either CHUNK_SIZE or the remaining bytes, whichever is smaller.
                bytes_in_current_chunk = min(CHUNK_SIZE, bytes_to_decrypt - bytes_read)
                chunk = infile.read(bytes_in_current_chunk)
                if not chunk: # Should not happen if file size calculations are correct
                    break
                plaintext_chunk = decryptor.update(chunk)
                outfile.write(plaintext_chunk)
                bytes_read += len(chunk)

            # Finalize the decryption. The tag is passed here for integrity verification.
            # If the tag does not match (due to tampering or wrong key), an InvalidTag
            # exception is raised, preventing the use of corrupt or malicious data.
            decryptor.finalize_with_tag(tag)

        print(f"Success: File '{input_filepath}' decrypted to '{output_filepath}'.")

    except FileNotFoundError:
        print(f"Error: Input file '{input_filepath}' not found.")
    except InvalidTag:
        print("Error: Decryption failed. The file may have been tampered with or the key is incorrect.")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred during decryption: {e}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="""Simple File Encryptor/Decryptor using AES-256 GCM.
This script allows you to generate a secure key, encrypt files, and decrypt them.
It uses authenticated encryption (AES GCM) to ensure both confidentiality and integrity.""",
        formatter_class=argparse.RawTextHelpFormatter # Keeps newlines in description
    )

    # Group for mutually exclusive actions (you can only generate a key OR encrypt OR decrypt)
    action_group = parser.add_mutually_exclusive_group(required=True)
    action_group.add_argument(
        '--generate-key',
        action='store_true',
        help='Generate a new random base64-encoded encryption key (256-bit AES).'
    )
    action_group.add_argument(
        '--encrypt',
        action='store_true',
        help='Encrypt the specified input file using the provided key.'
    )
    action_group.add_argument(
        '--decrypt',
        action='store_true',
        help='Decrypt the specified input file using the provided key.'
    )

    # Common arguments for encryption/decryption
    parser.add_argument(
        '--input',
        type=str,
        help='Path to the input file (original for encrypt, encrypted for decrypt).'
    )
    parser.add_argument(
        '--output',
        type=str,
        help='Path for the output file (encrypted for encrypt, decrypted for decrypt).'
    )
    parser.add_argument(
        '--key',
        type=str,
        help='The base64-encoded encryption key. Required for --encrypt and --decrypt.'
    )

    args = parser.parse_args()

    if args.generate_key:
        new_key = generate_key()
        print(f"\nGenerated AES-256 GCM Key: {new_key}")
        print("IMPORTANT: Keep this key secret and safe! It is needed for both encryption and decryption.\n")
    elif args.encrypt or args.decrypt:
        # Check if required arguments are provided for encryption/decryption
        if not args.input:
            parser.error("Argument --input is required for --encrypt or --decrypt.")
        if not args.output:
            parser.error("Argument --output is required for --encrypt or --decrypt.")
        if not args.key:
            parser.error("Argument --key is required for --encrypt or --decrypt.")

        if args.encrypt:
            encrypt_file(args.input, args.output, args.key)
        elif args.decrypt:
            decrypt_file(args.input, args.output, args.key)
